# Dockerfile for nginx_server
FROM nginx:latest

# Install Git
RUN apt-get update && apt-get install -y git

# Remove any existing files in the document root
RUN rm -rf /usr/share/nginx/html/*

# Clone the GitHub repository into the document root
RUN git clone https://github.com/naveedharri/webMidterm.git /usr/share/nginx/html/

# Ensure the necessary permissions
RUN chmod -R 755 /usr/share/nginx/html/

EXPOSE 80
