version: '3.8'
services:
  httpd_server:
    build:
      context: .
      dockerfile: Dockerfile.httpd_server   
    container_name: myapp-prod
    ports:
      - "8081:80"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
    restart: unless-stopped

